### ISSUE TITLE
Not sure if script is working

### ISSUE THREAD

**Issue by brianjw** [uupaa/EthOSHelper.js#1]
Attempted to set this up following the readme, but it doesn't seem like it's working. I added "/usr/bin/node --experimental-modules /home/ethos/ethos-agent/index.mjs" to the rc.local file and did not include the "+". Let me know if the + should be in the front - although I already tried it with the + in front.

When I had the "simulate_problem": true, I never received a slack message, even though I added my own slack web hook url. Additionally, the log file does not appear to exist yet which I believe to mean nothing has been posted to the log which should be in /tmp/ethos-agent.log.

I guess I'll find out in a few hours to a day when one of my GPU's crash. Let me know if you have any tips for this.

**Comment by uupaa** [comment]
@brianjw Thank you for giving me good advice.

Update README.md and made the following changes.

- add rc.local `+` mark comment.
    - > leading `+` is a symbol for diff on description, it's do not need to add it.
- remove "debug.simulate_problem"
- remove "watch.log"
- add test/notify.mjs
- add test/reboot.mjs
